spring:
  config:
    import: optional:file:.env[.properties]   # .env 읽기
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

jwt:
  secret: ${JWT_SECRET}
  issuer: itdaing-server
  access-token-expiration: ${JWT_ACCESS_EXP_MS:86400000}