name: BE CI
on:
  pull_request:
    branches: [ "dev/integration", "main" ]
    paths:
      - 'build.gradle.kts'
      - 'settings.gradle*'
      - 'gradle/**'
      - 'src/**'
      - '.github/workflows/be-ci.yml'
jobs:
  be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Gradle Test
        run: |
          ./gradlew --version
          ./gradlew clean test -i
